'use strict';
// OFFLINE_DOM_ONLY: no browser layout or Minecraft runtime evidence.
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const { JSDOM, VirtualConsole } = require(path.join(process.env.LOCALAPPDATA, 'Temp/itemguard-ux-check/node_modules/jsdom'));
const root = __dirname;
const report = { evidence: 'OFFLINE_DOM_ONLY', limitations: ['dialog.showModal/close stubbed for jsdom', 'no real browser pixels/layout', 'no native Minecraft inventory/Paper', 'no database/HavenBags API invocation'], variants: [] };
for (const variant of ['catalog-direct', 'catalog-guided']) {
  const html = fs.readFileSync(path.join(root, variant, 'index.html'), 'utf8');
  const errors = [];
  const vc = new VirtualConsole();
  vc.on('jsdomError', e => errors.push(e.message));
  const dom = new JSDOM(html, { runScripts: 'dangerously', url: 'https://offline.invalid/', virtualConsole: vc, beforeParse(w) {
    w.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
    w.HTMLDialogElement.prototype.close = function () { this.open = false; };
  } });
  const w = dom.window, d = w.document;
  const results = [];
  const q = s => d.querySelector(s);
  const slot = n => q('[data-slot="' + n + '"]');
  const title = () => q('#screen-title').textContent;
  const click = n => { assert.equal(slot(n).disabled, false, 'slot ' + n + ' enabled'); slot(n).click(); };
  const named = name => { const b = [...d.querySelectorAll('#grid button')].find(e => e.getAttribute('aria-label') === name); assert.ok(b, name); assert.equal(b.disabled, false); b.click(); };
  const reset = () => { q('#demo-reset').click(); if (variant === 'catalog-guided') click(20); };
  const query = value => { click(1); assert.ok(q('#query-dialog').open); q('#query').value = value; q('#query-form').dispatchEvent(new w.Event('submit', { bubbles: true, cancelable: true })); assert.equal(q('#query-dialog').open, false); };
  const dataSlots = () => [...d.querySelectorAll('#grid button')].filter(e => +e.dataset.slot >= 9 && +e.dataset.slot <= 44 && !e.disabled);
  const test = (name, fn) => { try { fn(); results.push({ name, pass: true }); } catch (e) { results.push({ name, pass: false, error: e.message }); } };
  test('script syntax and full CSS retained', () => { assert.deepEqual(errors, []); assert.ok(!html.includes('... [truncated')); assert.ok(html.includes('.lore h3{')); assert.ok(html.includes('@media(max-width:600px)')); });
  test('variant entry stance', () => { assert.match(title(), variant === 'catalog-guided' ? /Bạn muốn tra gì/ : /Kho tra cứu/); });
  test('54 slots and 36 page results', () => { reset(); assert.equal(d.querySelectorAll('#grid button').length, 54); assert.equal(dataSlots().length, 36); assert.equal(slot(8).disabled, true); assert.ok(slot(0).title.includes('không') || slot(0).title.includes('Không')); });
  test('pager buffers and second page content', () => { reset(); for (const i of [46,48,50,52]) assert.equal(slot(i).disabled, true); click(51); assert.equal(dataSlots().length, 4); assert.equal(slot(49).textContent, 'Trang 2/2'); assert.equal(slot(51).disabled, true); click(47); assert.equal(dataSlots().length, 36); });
  test('detail back preserves second page', () => { reset(); click(51); click(9); assert.match(title(), /Hồ sơ/); click(45); assert.equal(slot(49).textContent, 'Trang 2/2'); });
  test('category filter and clear', () => { reset(); click(2); named('Giáp'); assert.ok(dataSlots().length > 0); for (const e of dataSlots()) assert.match(e.title, /Giáp/); assert.equal(slot(8).disabled, false); click(8); assert.equal(dataSlots().length, 36); });
  test('source plus storage retain independent meanings', () => { reset(); click(3); named('MMOItems'); click(5); named('HavenBags'); assert.equal(dataSlots().length, 1); assert.match(dataSlots()[0].title, /Kiếm Bình Minh/); assert.match(dataSlots()[0].title, /Nguồn: MMOItems/); assert.match(dataSlots()[0].title, /Nơi thấy: HavenBags/); });
  test('person is last observed holder', () => { reset(); click(4); assert.match(title(), /giữ gần nhất/); named('Lan'); assert.equal(dataSlots().length, 2); for (const e of dataSlots()) assert.match(e.title, /Giữ gần nhất: Lan/); });
  test('status conflict not single authoritative holder', () => { reset(); click(6); named('! Nhiều bản quan sát'); assert.equal(dataSlots().length, 1); assert.match(dataSlots()[0].title, /Chưa chọn/); });
  test('sort changes order', () => { reset(); const first = slot(9).getAttribute('aria-label'); click(7); assert.notEqual(slot(9).getAttribute('aria-label'), first); });
  test('exact six-character search and dialog cancellation', () => { reset(); query('K7Q2MX'); assert.equal(dataSlots().length, 1); click(1); q('#query').value = 'not-applied'; q('#cancel-query').click(); assert.equal(dataSlots().length, 1); assert.equal(q('#query-dialog').open, false); });
  test('timeline carries time and gaps', () => { reset(); query('K7Q2MX'); named('Kiếm Bình Minh'); click(20); assert.match(title(), /Lịch sử/); named('13:50 · Thiếu đoạn chuyển'); assert.match(q('#lore-body').textContent, /Thiếu event/); assert.match(q('#lore-body').textContent, /\+07/); });
  test('holder chain preserves A to B to A', () => { reset(); query('K7Q2MX'); named('Kiếm Bình Minh'); click(22); const labels = dataSlots().map(e => e.getAttribute('aria-label')); assert.deepEqual(labels.slice(0,4), ['An · 13:00','Minh · 13:30','An · 13:50','Lan · 14:10']); named('Đọc chuỗi này'); assert.match(q('#lore-body').textContent, /Không khẳng định chủ sở hữu hợp pháp/); });
  test('bag owner versus carrier and nested return', () => { reset(); query('K7Q2MX'); named('Kiếm Bình Minh'); click(24); named('Chủ túi: Minh'); assert.match(q('#lore-body').textContent, /Không đồng nghĩa người cầm/); named('Cầm túi: Lan'); named('Hồ sơ chiếc túi'); assert.match(title(), /BAG4R2/); click(20); click(45); click(45); assert.match(title(), /Nơi lưu.*K7Q2MX/); click(45); click(45); assert.match(title(), /Kho tra cứu/); assert.equal(dataSlots().length, 1); });
  test('technical view keeps modifier separate', () => { reset(); query('K7Q2MX'); named('Kiếm Bình Minh'); click(31); named('Plugin tác động'); assert.match(q('#lore-body').textContent, /BastionForge.*MMOItems/); assert.match(q('#lore-body').textContent, /Không ghi đè nguồn/); });
  test('other items do not inherit demo chain', () => { reset(); query('ARM9X1'); named('Giáp hộ vệ'); click(20); assert.match(d.querySelector('#grid').textContent, /Lịch sử chưa đủ/); });
  test('empty is not absence and clear works', () => { reset(); q('#demo-empty').click(); assert.match(q('#feedback').textContent, /không có nghĩa item đã mất/); named('Không có kết quả'); assert.equal(dataSlots().length, 36); });
  test('query error is not empty and has no fake total', () => { reset(); q('#demo-error').click(); assert.equal(slot(49).textContent, 'Chưa tải'); assert.equal(slot(47).disabled, true); assert.equal(slot(51).disabled, true); named('Không tải được'); assert.equal(dataSlots().length, 36); });
  test('partial coverage visible at page level', () => { reset(); assert.match(q('#subline').textContent, /Kết quả chưa đầy đủ/); click(0); assert.match(q('#lore-body').textContent, /chưa kiểm tra được/); assert.match(title(), /Kho tra cứu/); });
  test('close and reopen preserve filters', () => { reset(); query('K7Q2MX'); click(53); assert.match(title(), /Đã đóng/); named('Mở lại'); assert.equal(dataSlots().length, 1); });
  test('guided entry selectors accessible without back loop', () => { reset(); click(45); assert.equal(slot(45).disabled, true); named('Theo người chơi'); assert.match(title(), /Người giữ gần nhất/); click(45); click(45); named('Theo nơi lưu'); assert.match(title(), /Nơi lưu/); });
  test('no errors and no external resources', () => { assert.deepEqual(errors, []); assert.equal(d.querySelectorAll('script[src],link[rel="stylesheet"],img[src],iframe').length, 0); for (const e of d.querySelectorAll('a[href]')) assert.ok(fs.existsSync(path.resolve(root, variant, e.getAttribute('href')))); });
  report.variants.push({ variant, sha256: crypto.createHash('sha256').update(html).digest('hex'), cases: results.length, failures: results.filter(x => !x.pass).length, results });
  dom.window.close();
}
const a = fs.readFileSync(path.join(root, 'catalog-direct/index.html'), 'utf8');
const b = fs.readFileSync(path.join(root, 'catalog-guided/index.html'), 'utf8');
report.sharedTemplateExact = a.replace("const VARIANT='direct';", "const VARIANT='guided';") === b;
report.cases = report.variants.reduce((s,x) => s+x.cases,0);
report.failures = report.variants.reduce((s,x) => s+x.failures,0) + (report.sharedTemplateExact ? 0 : 1);
fs.writeFileSync(path.join(root, 'verification.json'), JSON.stringify(report, null, 2)+'\n');
console.log(JSON.stringify({ evidence:report.evidence, cases:report.cases, failures:report.failures, sharedTemplateExact:report.sharedTemplateExact, variants:report.variants.map(x=>({variant:x.variant,cases:x.cases,failures:x.failures,failed:x.results.filter(t=>!t.pass)})) },null,2));
process.exitCode = report.failures ? 1 : 0;
